# Generated by Django 4.0.6 on 2022-07-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctor', to='hospital.doctor'),
        ),
    ]
